### ISSUE TITLE
Statically link SPIRV-Cross

### ISSUE THREAD

**Issue by thatcosmonaut** [libsdl-org/SDL_gpu_shadercross#37]
SPIRV-Cross is going to be required for any practical workflow and the core of the library depends on it, so we should just statically link it to avoid clients having to ship an extra dependency.

**Comment by TheSpydog** [comment]
I’m not sure what you mean. The majority of FNA3D platforms use the cross compiler. Windows/Xbox use it for D3D12, macOS/iOS/tvOS use it for Metal. Even Linux could use it if we wanted to target dxvk or whatever.

I don’t see a benefit for having it be dynamic outside of shedding ~1MB from the binary on Linux if we only care about Vulkan. Even in that case, if we want to be in the business of dealing with optional dependencies, we could just make shadercross itself optional since we’re emitting spirv from MojoShader anyway.

**Comment by flibitijibibo** [comment]
Fair enough - before updating FNA3D to use this repo as a submodule let's make shadercross optional in mojoshader_sdlgpu.c

**Comment by thatcosmonaut** [comment]
@madebr Would you be able to modify the build system to statically link SPIRV-Cross?

**Comment by TheSpydog** [comment]
It’d be great if we could avoid having a bunch of individual spirv-cross library files to link together. We could maybe directly integrate the source files into our project rather than using SPIRV-Cross’s CMake?

**Comment by thatcosmonaut** [comment]
I'm fine with that if it's more practical.

**Comment by TheSpydog** [comment]
To clarify, the only dependency we want to link with statically is SPIRV-Cross, since it’s fundamental to the entire operation of the library.

Everything else has to be dynamic, whether for licensing (vkd3d is LGPL) or practical reasons (dxcompiler [cannot be built as a static library](https://devlog.hexops.com/2024/building-the-directx-shader-compiler-better-than-microsoft/#well-why-not-just-statically-link-against-it) without significant changes).

It is convenient having vkd3d / dxcompiler dynamic libs built or fetched from the CMake script, so it’d be nice if we could keep that functionality intact.

**Comment by thatcosmonaut** [comment]
Resolved by https://github.com/libsdl-org/SDL_gpu_shadercross/commit/3385fb5c8b802abe8208ece01ffee6b5ef743867
