### ISSUE TITLE
Build dxcompiler dependency for MacOS

### ISSUE THREAD

**Issue by thatcosmonaut** [libsdl-org/SDL_gpu_shadercross#38]
This is required for cross-platform HLSL workflows.

**Comment by TheSpydog** [comment]
It’d be really nice if we could, but…

https://devlog.hexops.com/2024/building-the-directx-shader-compiler-better-than-microsoft/#well-why-not-just-statically-link-against-it

I wonder if the situation has improved at all since this blog post was written. Integrating DXIL signing into dxcompiler itself solves at least that problem, but I have no idea about the build system.

**Comment by thatcosmonaut** [comment]
This might be something we can do more easily once HLSL is upstreamed into clang.

**Comment by thatcosmonaut** [comment]
To recap:
- It's basically impossible to statically link dxcompiler at this time due to Microsoft's bungled build setup.
- The only scenarios where dxcompiler is actually needed at runtime are when clients are shipping HLSL source or when compiling SPIR-V to DXIL on Windows at runtime. At some point in the future even the latter workflow will be obsoleted as Microsoft plans to accept SPIR-V directly as a bytecode format.
- Microsoft doesn't provided libdxcompiler builds for MacOS, so we need to build and package it ourselves.
- At some point in the future when HLSL support is upstreamed into clang, we can revisit statically including dxcompiler.

**Comment by thatcosmonaut** [comment]
Resolved by https://github.com/libsdl-org/SDL_gpu_shadercross/commit/933e058bc2f442461b4358b3fc2e896c34775478
